name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2. Install Dependencies (The "npm install" step)
      - name: Install Dependencies
        run: npm ci

      # 3. Create the Secret Config File (The robot needs the password too!)
      - name: Create Cypress Env File
        run: |
          echo '{
            "adminEmail": "${{ secrets.ADMIN_EMAIL }}",
            "adminPassword": "${{ secrets.ADMIN_PASSWORD }}"
          }' > cypress.env.json

      # 4. Run the Test (Headless)
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server -p 5500 . # Starts your local server in the cloud
          wait-on: 'http://127.0.0.1:5500' # Waits for it to be ready